//go:build ignore

// Command gen_adobe_gb1 regenerates adobe_gb1_data.go from Adobe's Adobe-GB1
// CID→Unicode table.
//
// The table ships with poppler-data, which redistributes Adobe's CMap data
// under BSD-3-Clause. Poppler installs it under /usr/share/poppler; override
// with -poppler when it lives elsewhere (macOS Homebrew, Nix, a container
// image, or a checkout of https://gitlab.freedesktop.org/poppler/poppler-data).
//
// Run from the fontfix directory:
//
//	go generate ./...
//
// The generated file is committed so that building fontfix never requires
// poppler-data to be installed. Regenerating is only needed when switching to a
// different Adobe-GB1 revision.
package main

import (
	"bytes"
	"compress/zlib"
	"encoding/base64"
	"encoding/binary"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

var popplerDir = flag.String("poppler", "/usr/share/poppler", "directory containing cidToUnicode/Adobe-GB1")

func main() {
	flag.Parse()
	source := filepath.Join(*popplerDir, "cidToUnicode", "Adobe-GB1")
	data, err := os.ReadFile(source)
	if err != nil {
		log.Fatalf("read %s: %v (point -poppler at the poppler-data installation)", source, err)
	}
	codes := parseCIDToUnicode(string(data))
	if len(codes) != 30284 {
		log.Fatalf("parsed %d entries, want 30284; the data format may have changed", len(codes))
	}
	packed, err := pack(codes)
	if err != nil {
		log.Fatalf("compress table: %v", err)
	}
	source_code, err := render(packed, supplementary(codes))
	if err != nil {
		log.Fatalf("render source: %v", err)
	}
	if err := os.WriteFile("adobe_gb1_data.go", source_code, 0o644); err != nil {
		log.Fatalf("write output: %v", err)
	}
	fmt.Printf("wrote adobe_gb1_data.go: %d CIDs, %d bytes compressed\n", len(codes), len(packed))
}

// parseCIDToUnicode reads poppler's cidToUnicode/Adobe-GB1, a single column of
// hex Unicode values whose line number is the CID.
func parseCIDToUnicode(text string) []uint32 {
	var codes []uint32
	for index, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		value, err := strconv.ParseUint(line, 16, 32)
		if err != nil {
			log.Fatalf("line %d: %q is not hexadecimal: %v", index+1, line, err)
		}
		codes = append(codes, uint32(value))
	}
	return codes
}

// pack stores the table as big-endian uint16 (values above the BMP are stored as
// 0 and carried by a sparse supplementary-plane list instead) and deflates it,
// because 30284 raw uint16s would be roughly 240KB of Go source.
func pack(codes []uint32) ([]byte, error) {
	raw := make([]byte, 0, len(codes)*2)
	for _, code := range codes {
		value := uint16(0)
		if code <= 0xFFFF {
			value = uint16(code)
		}
		raw = binary.BigEndian.AppendUint16(raw, value)
	}
	var compressed bytes.Buffer
	writer, err := zlib.NewWriterLevel(&compressed, zlib.BestCompression)
	if err != nil {
		return nil, err
	}
	if _, err := writer.Write(raw); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return compressed.Bytes(), nil
}

// supplementary lists the CIDs whose Unicode is above the BMP, which the packed
// uint16 table cannot hold.
func supplementary(codes []uint32) [][3]uint32 {
	var out [][3]uint32
	for cid, code := range codes {
		if code > 0xFFFF {
			out = append(out, [3]uint32{uint32(cid), 0, code})
		}
	}
	return out
}

// render writes the generated Go source, split into base64 chunks so no single
// line in the repository is pathologically long.
func render(packed []byte, supplement [][3]uint32) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(header)
	const chunk = 96
	encoded := base64.StdEncoding.EncodeToString(packed)
	out.WriteString("const adobeGB1Packed = \"\" +\n")
	for start := 0; start < len(encoded); start += chunk {
		end := min(start+chunk, len(encoded))
		separator := " +\n"
		if end == len(encoded) {
			separator = "\n"
		}
		fmt.Fprintf(&out, "\t%q%s", encoded[start:end], separator)
	}
	out.WriteString("\n// adobeGB1Supplementary carries the CIDs whose Unicode is above the BMP, which\n")
	out.WriteString("// the uint16 table cannot hold. Entries are {CID, _, Unicode}.\n")
	out.WriteString("var adobeGB1Supplementary = [][3]uint32{\n")
	for _, entry := range supplement {
		fmt.Fprintf(&out, "\t{%d, 0, 0x%X},\n", entry[0], entry[2])
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

const header = `// Code generated by gen_adobe_gb1.go; DO NOT EDIT.

// Regenerate with ` + "`go generate ./...`" + ` in the fontfix directory. The generator reads
// Adobe's Adobe-GB1 CID→Unicode table as redistributed by poppler-data
// (BSD-3-Clause, Copyright 1990-2018 Adobe Systems Incorporated); see NOTICE
// for the full notice.
//
// The table is deflated because 30284 uint16 values as a Go slice literal would
// be roughly 240KB of source. Unicode above the BMP does not fit in uint16 and is
// carried by adobeGB1Supplementary instead.

package fontfix

// adobeGB1CIDs is the number of CIDs covered by the table. Adobe-GB1 defines
// CID 0 through 30283.
const adobeGB1CIDs = 30284

// adobeGB1Unmapped is the number of CIDs in the table that carry no Unicode:
// CID 0 (.notdef), a few unassigned slots, and the contiguous block 22127-22352
// plus its neighbours that Adobe-GB1 added without assigning characters.
const adobeGB1Unmapped = ` + "274" + `

// adobeGB1Packed is the deflated Adobe-GB1 CID→Unicode table: CID c maps to the
// big-endian uint16 at offset c*2. Zero means the CID has no mapping, or its
// Unicode lives in the supplementary plane.
`
